// <auto-generated />
using DavaoCityExplorerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DavaoCityExplorerAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204115236_AddInitialData4Categories")]
    partial class AddInitialData4Categories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DavaoCityExplorerAPI.Models.CategoryModel", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImageID")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.HasIndex("ImageID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Description = "From the majestic peaks of Mt. Apo to the sanctuary of the Philippine Eagle, witness the icons that define the South.",
                            ImageID = 1,
                            Path = "/attractions",
                            Title = "Discover Nature’s Grandest Stage"
                        },
                        new
                        {
                            CategoryID = 2,
                            Description = "Hunt for authentic pearls, weave through bustling night markets, or enjoy world-class retail therapy in the heart of the city.",
                            ImageID = 2,
                            Path = "/shopping",
                            Title = "Malls, Markets & Memories"
                        },
                        new
                        {
                            CategoryID = 3,
                            Description = "Experience the vibrant nightlife, live local music, and the festive spirit that comes alive when the sun goes down.",
                            ImageID = 3,
                            Path = "/entertainment",
                            Title = "The Pulse of the City"
                        },
                        new
                        {
                            CategoryID = 4,
                            Description = "Whether you seek 5-star luxury by the sea or a cozy backpacker’s haven, find your perfect sanctuary here.",
                            ImageID = 4,
                            Path = "/accommodation",
                            Title = "Your Home in the South"
                        },
                        new
                        {
                            CategoryID = 5,
                            Description = "Dare to taste the King of Fruits, savor the freshest Tuna, and dive into a culinary landscape you won’t find anywhere else.",
                            ImageID = 5,
                            Path = "/foodscene",
                            Title = "A Feast of Flavors"
                        },
                        new
                        {
                            CategoryID = 6,
                            Description = "Walk through time at the museums, meet the 11 tribes, and discover the rich heritage that weaves the city together.",
                            ImageID = 6,
                            Path = "/art&museum",
                            Title = "The Soul of Davao"
                        });
                });

            modelBuilder.Entity("DavaoCityExplorerAPI.Models.ImageModel", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageID");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageID = 1,
                            ImageURL = "/images/masonry-attractions.webp",
                            Name = "Davao City Hall"
                        },
                        new
                        {
                            ImageID = 2,
                            ImageURL = "/images/masonry-shopping.webp",
                            Name = "Davao Downtown Area"
                        },
                        new
                        {
                            ImageID = 3,
                            ImageURL = "/images/masonry-entertainment.webp",
                            Name = "Davao Clubs"
                        },
                        new
                        {
                            ImageID = 4,
                            ImageURL = "/images/masonry-accommodations.webp",
                            Name = "Marco Polo Building"
                        },
                        new
                        {
                            ImageID = 5,
                            ImageURL = "/images/masonry-foodscene.webp",
                            Name = "Roxas Night Market"
                        },
                        new
                        {
                            ImageID = 6,
                            ImageURL = "/images/masonry-art&museum.webp",
                            Name = "Davao Museum"
                        });
                });

            modelBuilder.Entity("DavaoCityExplorerAPI.Models.PlaceModel", b =>
                {
                    b.Property<int>("PlaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaceID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("ImageID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("PlaceID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ImageID");

                    b.HasIndex("TagID");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("DavaoCityExplorerAPI.Models.TagModel", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagID");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DavaoCityExplorerAPI.Models.CategoryModel", b =>
                {
                    b.HasOne("DavaoCityExplorerAPI.Models.ImageModel", "Image")
                        .WithMany()
                        .HasForeignKey("ImageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("DavaoCityExplorerAPI.Models.PlaceModel", b =>
                {
                    b.HasOne("DavaoCityExplorerAPI.Models.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DavaoCityExplorerAPI.Models.ImageModel", "Image")
                        .WithMany()
                        .HasForeignKey("ImageID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DavaoCityExplorerAPI.Models.TagModel", "Tag")
                        .WithMany()
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Image");

                    b.Navigation("Tag");
                });
#pragma warning restore 612, 618
        }
    }
}
