// <auto-generated />
using DavaoCityExplorerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DavaoCityExplorerAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260205131336_AddPlaceTagsRelationship")]
    partial class AddPlaceTagsRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DavaoCityExplorerAPI.Models.CategoryModel", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImageID")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.HasIndex("ImageID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Description = "From the majestic peaks of Mt. Apo to the sanctuary of the Philippine Eagle, witness the icons that define the South.",
                            ImageID = 1,
                            Path = "/attractions",
                            Title = "Discover Nature’s Grandest Stage"
                        },
                        new
                        {
                            CategoryID = 2,
                            Description = "Hunt for authentic pearls, weave through bustling night markets, or enjoy world-class retail therapy in the heart of the city.",
                            ImageID = 2,
                            Path = "/shopping",
                            Title = "Malls, Markets & Memories"
                        },
                        new
                        {
                            CategoryID = 3,
                            Description = "Experience the vibrant nightlife, live local music, and the festive spirit that comes alive when the sun goes down.",
                            ImageID = 3,
                            Path = "/entertainment",
                            Title = "The Pulse of the City"
                        },
                        new
                        {
                            CategoryID = 4,
                            Description = "Whether you seek 5-star luxury by the sea or a cozy backpacker’s haven, find your perfect sanctuary here.",
                            ImageID = 4,
                            Path = "/accommodation",
                            Title = "Your Home in the South"
                        },
                        new
                        {
                            CategoryID = 5,
                            Description = "Dare to taste the King of Fruits, savor the freshest Tuna, and dive into a culinary landscape you won’t find anywhere else.",
                            ImageID = 5,
                            Path = "/foodscene",
                            Title = "A Feast of Flavors"
                        },
                        new
                        {
                            CategoryID = 6,
                            Description = "Walk through time at the museums, meet the 11 tribes, and discover the rich heritage that weaves the city together.",
                            ImageID = 6,
                            Path = "/art&museum",
                            Title = "The Soul of Davao"
                        });
                });

            modelBuilder.Entity("DavaoCityExplorerAPI.Models.ImageModel", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageID");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageID = 1,
                            ImageURL = "/images/masonry-attractions.webp",
                            Name = "Davao City Hall"
                        },
                        new
                        {
                            ImageID = 2,
                            ImageURL = "/images/masonry-shopping.webp",
                            Name = "Davao Downtown Area"
                        },
                        new
                        {
                            ImageID = 3,
                            ImageURL = "/images/masonry-entertainment.webp",
                            Name = "Davao Clubs"
                        },
                        new
                        {
                            ImageID = 4,
                            ImageURL = "/images/masonry-accommodations.webp",
                            Name = "Marco Polo Building"
                        },
                        new
                        {
                            ImageID = 5,
                            ImageURL = "/images/masonry-foodscene.webp",
                            Name = "Roxas Night Market"
                        },
                        new
                        {
                            ImageID = 6,
                            ImageURL = "/images/masonry-art&museum.webp",
                            Name = "Davao Museum"
                        },
                        new
                        {
                            ImageID = 7,
                            ImageURL = "/images/eagle-center.webp",
                            Name = "Philippine Eagle Center"
                        },
                        new
                        {
                            ImageID = 8,
                            ImageURL = "/images/eden-park.webp",
                            Name = "Eden's Nature Park"
                        },
                        new
                        {
                            ImageID = 9,
                            ImageURL = "/images/peoples-park.webp",
                            Name = "People's Park"
                        },
                        new
                        {
                            ImageID = 11,
                            ImageURL = "/images/poblacion-market.webp",
                            Name = "Poblacion Market Central"
                        },
                        new
                        {
                            ImageID = 12,
                            ImageURL = "/images/abreeza-mall.webp",
                            Name = "Abreeza Mall"
                        },
                        new
                        {
                            ImageID = 13,
                            ImageURL = "/images/matina-town-square.webp",
                            Name = "Matina Town Square"
                        },
                        new
                        {
                            ImageID = 14,
                            ImageURL = "/images/jack-ridge.webp",
                            Name = "Jack's Ridge"
                        },
                        new
                        {
                            ImageID = 15,
                            ImageURL = "/images/huckleberry-kitchen.webp",
                            Name = "Huckleberry Southern Kitchen"
                        },
                        new
                        {
                            ImageID = 16,
                            ImageURL = "/images/pearl-farm.webp",
                            Name = "Pearl Farm Beach Resort"
                        },
                        new
                        {
                            ImageID = 17,
                            ImageURL = "/images/abreeza-hotel.webp",
                            Name = "Seda Abreeza Hotel"
                        },
                        new
                        {
                            ImageID = 18,
                            ImageURL = "/images/malagos-resort.webp",
                            Name = "Malagos Garden Resort"
                        },
                        new
                        {
                            ImageID = 19,
                            ImageURL = "/images/yellowfin-restaurant.webp",
                            Name = "Yellow Fin Seafood Restaurant"
                        },
                        new
                        {
                            ImageID = 20,
                            ImageURL = "/images/wishbone-restaurant.webp",
                            Name = "The Wishbone Matina"
                        },
                        new
                        {
                            ImageID = 21,
                            ImageURL = "/images/penongs-restaurant.webp",
                            Name = "Penongs Matina Branch"
                        },
                        new
                        {
                            ImageID = 22,
                            ImageURL = "/images/davao-museum.webp",
                            Name = "Davao Museum of History"
                        },
                        new
                        {
                            ImageID = 23,
                            ImageURL = "/images/bone-museum.webp",
                            Name = "D' Bone Collector Museum"
                        },
                        new
                        {
                            ImageID = 24,
                            ImageURL = "/images/kublai-art-garden.webp",
                            Name = "Kublai Art Garden"
                        });
                });

            modelBuilder.Entity("DavaoCityExplorerAPI.Models.PlaceModel", b =>
                {
                    b.Property<int>("PlaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaceID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("ImageID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("PlaceID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ImageID");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            PlaceID = 1,
                            CategoryID = 1,
                            ImageID = 7,
                            Location = "Malagos, Baguio District",
                            Name = "Philippine Eagle Center",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            PlaceID = 2,
                            CategoryID = 1,
                            ImageID = 8,
                            Location = "Toril, Davao City",
                            Name = "Eden Nature Park",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            PlaceID = 3,
                            CategoryID = 1,
                            ImageID = 9,
                            Location = "Palma Gil St, Poblacion",
                            Name = "People's Park",
                            Rating = 4.5
                        },
                        new
                        {
                            PlaceID = 4,
                            CategoryID = 2,
                            ImageID = 5,
                            Location = "Roxas Avenue",
                            Name = "Roxas Night Market",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            PlaceID = 5,
                            CategoryID = 2,
                            ImageID = 11,
                            Location = "C. Bangoy St, Poblacion",
                            Name = "Poblacion Market Central",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            PlaceID = 6,
                            CategoryID = 2,
                            ImageID = 12,
                            Location = "J.P. Laurel Ave, Poblacion District",
                            Name = "Abreeza Mall",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            PlaceID = 7,
                            CategoryID = 3,
                            ImageID = 13,
                            Location = "McArthur Highway, Matina",
                            Name = "Matina Town Square (MTS)",
                            Rating = 4.5
                        },
                        new
                        {
                            PlaceID = 8,
                            CategoryID = 3,
                            ImageID = 14,
                            Location = "Shrine Hills, Matina",
                            Name = "Jack's Ridge",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            PlaceID = 9,
                            CategoryID = 3,
                            ImageID = 15,
                            Location = "Oboza Compound, Rizal St",
                            Name = "Huckleberry Southern Kitchen",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            PlaceID = 10,
                            CategoryID = 4,
                            ImageID = 16,
                            Location = "Samal Island",
                            Name = "Pearl Farm Beach Resort",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            PlaceID = 11,
                            CategoryID = 4,
                            ImageID = 17,
                            Location = "J.P. Laurel Ave, Bajada",
                            Name = "Seda Abreeza Hotel",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            PlaceID = 12,
                            CategoryID = 4,
                            ImageID = 18,
                            Location = "Malagos, Calinan",
                            Name = "Malagos Garden Resort",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            PlaceID = 13,
                            CategoryID = 5,
                            ImageID = 19,
                            Location = "Quimpo Blvd, Ecoland",
                            Name = "Yellow Fin Seafood Restaurant",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            PlaceID = 14,
                            CategoryID = 5,
                            ImageID = 20,
                            Location = "Water District Matina, Along Gen. Douglas MacArthur Hwy,",
                            Name = "The Wishbone",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            PlaceID = 15,
                            CategoryID = 5,
                            ImageID = 21,
                            Location = "Erya Bldg, Pag-Asa Village",
                            Name = "Penong's Matina Aplaya",
                            Rating = 4.5
                        },
                        new
                        {
                            PlaceID = 16,
                            CategoryID = 6,
                            ImageID = 22,
                            Location = "Insular Village, Lanang",
                            Name = "Davao Museum of History",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            PlaceID = 17,
                            CategoryID = 6,
                            ImageID = 23,
                            Location = "San Pedro St, Poblacion",
                            Name = "D' Bone Collector Museum",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            PlaceID = 18,
                            CategoryID = 6,
                            ImageID = 24,
                            Location = "Kapatagan, Digos (Nearby)",
                            Name = "Kublai Art Garden",
                            Rating = 4.7000000000000002
                        });
                });

            modelBuilder.Entity("DavaoCityExplorerAPI.Models.PlaceTagModel", b =>
                {
                    b.Property<int>("PlaceID")
                        .HasColumnType("int");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("PlaceID", "TagID");

                    b.ToTable("PlaceTags");

                    b.HasData(
                        new
                        {
                            PlaceID = 1,
                            TagID = 1
                        },
                        new
                        {
                            PlaceID = 1,
                            TagID = 2
                        },
                        new
                        {
                            PlaceID = 1,
                            TagID = 3
                        },
                        new
                        {
                            PlaceID = 2,
                            TagID = 4
                        },
                        new
                        {
                            PlaceID = 2,
                            TagID = 5
                        },
                        new
                        {
                            PlaceID = 2,
                            TagID = 6
                        },
                        new
                        {
                            PlaceID = 3,
                            TagID = 7
                        },
                        new
                        {
                            PlaceID = 3,
                            TagID = 8
                        },
                        new
                        {
                            PlaceID = 3,
                            TagID = 25
                        },
                        new
                        {
                            PlaceID = 4,
                            TagID = 9
                        },
                        new
                        {
                            PlaceID = 4,
                            TagID = 12
                        },
                        new
                        {
                            PlaceID = 4,
                            TagID = 13
                        },
                        new
                        {
                            PlaceID = 5,
                            TagID = 14
                        },
                        new
                        {
                            PlaceID = 5,
                            TagID = 15
                        },
                        new
                        {
                            PlaceID = 5,
                            TagID = 16
                        },
                        new
                        {
                            PlaceID = 6,
                            TagID = 17
                        },
                        new
                        {
                            PlaceID = 6,
                            TagID = 18
                        },
                        new
                        {
                            PlaceID = 6,
                            TagID = 19
                        },
                        new
                        {
                            PlaceID = 7,
                            TagID = 20
                        },
                        new
                        {
                            PlaceID = 7,
                            TagID = 21
                        },
                        new
                        {
                            PlaceID = 7,
                            TagID = 22
                        },
                        new
                        {
                            PlaceID = 8,
                            TagID = 23
                        },
                        new
                        {
                            PlaceID = 8,
                            TagID = 24
                        },
                        new
                        {
                            PlaceID = 8,
                            TagID = 25
                        },
                        new
                        {
                            PlaceID = 9,
                            TagID = 26
                        },
                        new
                        {
                            PlaceID = 9,
                            TagID = 27
                        },
                        new
                        {
                            PlaceID = 9,
                            TagID = 28
                        },
                        new
                        {
                            PlaceID = 10,
                            TagID = 19
                        },
                        new
                        {
                            PlaceID = 10,
                            TagID = 8
                        },
                        new
                        {
                            PlaceID = 11,
                            TagID = 23
                        },
                        new
                        {
                            PlaceID = 11,
                            TagID = 24
                        },
                        new
                        {
                            PlaceID = 11,
                            TagID = 19
                        },
                        new
                        {
                            PlaceID = 12,
                            TagID = 3
                        },
                        new
                        {
                            PlaceID = 12,
                            TagID = 2
                        },
                        new
                        {
                            PlaceID = 12,
                            TagID = 16
                        },
                        new
                        {
                            PlaceID = 13,
                            TagID = 24
                        },
                        new
                        {
                            PlaceID = 13,
                            TagID = 28
                        },
                        new
                        {
                            PlaceID = 14,
                            TagID = 24
                        },
                        new
                        {
                            PlaceID = 15,
                            TagID = 24
                        },
                        new
                        {
                            PlaceID = 16,
                            TagID = 25
                        },
                        new
                        {
                            PlaceID = 16,
                            TagID = 2
                        },
                        new
                        {
                            PlaceID = 16,
                            TagID = 3
                        },
                        new
                        {
                            PlaceID = 17,
                            TagID = 25
                        },
                        new
                        {
                            PlaceID = 17,
                            TagID = 2
                        },
                        new
                        {
                            PlaceID = 17,
                            TagID = 3
                        },
                        new
                        {
                            PlaceID = 18,
                            TagID = 25
                        },
                        new
                        {
                            PlaceID = 18,
                            TagID = 2
                        },
                        new
                        {
                            PlaceID = 18,
                            TagID = 16
                        });
                });

            modelBuilder.Entity("DavaoCityExplorerAPI.Models.TagModel", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagID");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagID = 1,
                            TagName = "Wildlife"
                        },
                        new
                        {
                            TagID = 2,
                            TagName = "Conservation"
                        },
                        new
                        {
                            TagID = 3,
                            TagName = "Nature"
                        },
                        new
                        {
                            TagID = 4,
                            TagName = "Mountain Resort"
                        },
                        new
                        {
                            TagID = 5,
                            TagName = "Adventure"
                        },
                        new
                        {
                            TagID = 6,
                            TagName = "Hiking"
                        },
                        new
                        {
                            TagID = 7,
                            TagName = "Public Park"
                        },
                        new
                        {
                            TagID = 8,
                            TagName = "Family"
                        },
                        new
                        {
                            TagID = 9,
                            TagName = "Street Food"
                        },
                        new
                        {
                            TagID = 12,
                            TagName = "Thrifting"
                        },
                        new
                        {
                            TagID = 13,
                            TagName = "Night Market"
                        },
                        new
                        {
                            TagID = 14,
                            TagName = "Souvenirs"
                        },
                        new
                        {
                            TagID = 15,
                            TagName = "Pearls"
                        },
                        new
                        {
                            TagID = 16,
                            TagName = "Handicrafts"
                        },
                        new
                        {
                            TagID = 17,
                            TagName = "Shopping Mall"
                        },
                        new
                        {
                            TagID = 18,
                            TagName = "Convention"
                        },
                        new
                        {
                            TagID = 19,
                            TagName = "Luxury"
                        },
                        new
                        {
                            TagID = 20,
                            TagName = "Live Bands"
                        },
                        new
                        {
                            TagID = 21,
                            TagName = "Food Park"
                        },
                        new
                        {
                            TagID = 22,
                            TagName = "Nightlife"
                        },
                        new
                        {
                            TagID = 23,
                            TagName = "City View"
                        },
                        new
                        {
                            TagID = 24,
                            TagName = "Dining"
                        },
                        new
                        {
                            TagID = 25,
                            TagName = "History"
                        },
                        new
                        {
                            TagID = 26,
                            TagName = "Cocktails"
                        },
                        new
                        {
                            TagID = 27,
                            TagName = "Heritage House"
                        },
                        new
                        {
                            TagID = 28,
                            TagName = "Bar"
                        });
                });

            modelBuilder.Entity("DavaoCityExplorerAPI.Models.CategoryModel", b =>
                {
                    b.HasOne("DavaoCityExplorerAPI.Models.ImageModel", "Image")
                        .WithMany()
                        .HasForeignKey("ImageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("DavaoCityExplorerAPI.Models.PlaceModel", b =>
                {
                    b.HasOne("DavaoCityExplorerAPI.Models.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DavaoCityExplorerAPI.Models.ImageModel", "Image")
                        .WithMany()
                        .HasForeignKey("ImageID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Image");
                });
#pragma warning restore 612, 618
        }
    }
}
